@baseUrl = http://127.0.0.1:3001
@apiPrefix = /api/v42
@jwt = REPLACE_WITH_JWT

###

GET {{baseUrl}}/

###

GET {{baseUrl}}{{apiPrefix}}/status

###

GET {{baseUrl}}{{apiPrefix}}/auth/spotify/login

###

GET {{baseUrl}}{{apiPrefix}}/auth/me
Authorization: Bearer {{jwt}}

###

GET {{baseUrl}}{{apiPrefix}}/auth/session-status
Authorization: Bearer {{jwt}}

###

POST {{baseUrl}}{{apiPrefix}}/auth/refresh
Authorization: Bearer {{jwt}}

###

GET {{baseUrl}}{{apiPrefix}}/spotify/player-token
Authorization: Bearer {{jwt}}

###

GET {{baseUrl}}{{apiPrefix}}/spotify/favorites?limit=10
Authorization: Bearer {{jwt}}

###

GET {{baseUrl}}{{apiPrefix}}/search?q=daft%20punk&type=track&limit=10
Authorization: Bearer {{jwt}}

###

GET {{baseUrl}}{{apiPrefix}}/search?q=zzzzzzzzzzzzzzzzzzzz&type=track&limit=5
Authorization: Bearer {{jwt}}
